name: App
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  App:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
      - path: Sources/Features
    settings:
      base:
        INFOPLIST_FILE: Sources/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"

  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: App
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/App.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/App"
