name: App
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.2"
    SWIFT_STRICT_CONCURRENCY: complete
    # コード署名設定
    # DEVELOPMENT_TEAM は環境変数から取得する。
    # ローカルビルド: export DEVELOPMENT_TEAM="YOUR_TEAM_ID"
    # CI: シークレットとして設定する
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"

targets:
  App:
    type: application
    platform: iOS
    sources:
      - path: Sources/App
      - path: Sources/Features
      - path: Sources/Shared
    settings:
      base:
        INFOPLIST_FILE: Sources/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.example.kokorouta
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFunctions

  AppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: App
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/App.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/App"

schemes:
  App:
    build:
      targets:
        App: all
        AppTests: [test]
    run:
      config: Debug
      environmentVariables:
        - variable: USE_EMULATOR
          value: "1"
          isEnabled: false
    test:
      config: Debug
      targets:
        - AppTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
